/**
* KMS OpenAPI Backend
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.kms.openapi.dto

import com.kms.openapi.dto.UserDto

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param objectId 
 * @param postId 
 * @param author 
 * @param content 
 * @param createdAt 
 * @param parentComment 
 */

data class CommentExtendedDto (
    @SerializedName("objectId")
    val objectId: kotlin.String,
    @SerializedName("postId")
    val postId: kotlin.String,
    @SerializedName("author")
    val author: UserDto,
    @SerializedName("content")
    val content: kotlin.String,
    @SerializedName("createdAt")
    val createdAt: java.time.Instant,
    @SerializedName("parentComment")
    val parentComment: CommentExtendedDto? = null
)

