/**
* KMS OpenAPI Backend
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.kms.openapi.dto

import com.kms.openapi.dto.UserDto

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param objectId 
 * @param title 
 * @param content 
 * @param author 
 * @param countThumbup 
 * @param countComment 
 * @param countRepost 
 * @param repliedAt 
 * @param parentPostId 
 * @param rootPostId 
 * @param parentPostTitle 
 * @param createdAt 
 * @param updatedAt 
 */

data class PostExtendedDto (
    @SerializedName("objectId")
    val objectId: kotlin.String,
    @SerializedName("title")
    val title: kotlin.String,
    @SerializedName("content")
    val content: kotlin.String,
    @SerializedName("author")
    val author: UserDto,
    @SerializedName("countThumbup")
    val countThumbup: kotlin.Int,
    @SerializedName("countComment")
    val countComment: kotlin.Int,
    @SerializedName("countRepost")
    val countRepost: kotlin.Int,
    @SerializedName("repliedAt")
    val repliedAt: java.time.Instant,
    @SerializedName("parentPostId")
    val parentPostId: kotlin.String? = null,
    @SerializedName("rootPostId")
    val rootPostId: kotlin.String? = null,
    @SerializedName("parentPostTitle")
    val parentPostTitle: kotlin.String? = null,
    @SerializedName("createdAt")
    val createdAt: java.time.Instant? = null,
    @SerializedName("updatedAt")
    val updatedAt: java.time.Instant? = null
)

