/**
* KMS OpenAPI Backend
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.kms.openapi.dto


import com.google.gson.annotations.SerializedName

/**
 * 
 * @param objectId 
 * @param nickname 
 * @param avatarUrl 
 */

data class UserDto (
    @SerializedName("objectId")
    val objectId: kotlin.String,
    @SerializedName("nickname")
    val nickname: kotlin.String,
    @SerializedName("avatarUrl")
    val avatarUrl: kotlin.String
)

