#!/usr/bin/env python3

import sys
import base64

SALT = b"example.me"

def encode(x):
    return base64.b64encode(base64.b64encode(SALT + x) + SALT)

for x in sys.argv[1:]:
    print(encode(x.encode("ascii")).decode("utf-8"))
