spring:
  application:
    name: kMSOpenAPIBackend

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

management:
  endpoints.web.base-path: /adminz
  endpoints.web.exposure.include: "*"